### ISSUE TITLE
Street Art Ft Lauderdale

### ISSUE THREAD

**Issue by jslusser** [CodeForFtL/project-ideas#12]
I would like to replicate a project that the Orlando Brigade did.  Street Art Ft Lauderdale will be a website and app that documents and catalogs art murals on buildings, allowing the user to see and learn about various murals on a map, and also the opportunity to add new murals.  I think there may we a walking tour component as well, but I’m not sure yet.

## Issue area(s) relevant to your project idea:

- Arts & Culture
- Children & Youth
- Education
- Neighborhoods

## What is the current state of your project idea?

- I have an idea or **concept** of a solution, but have not yet prototyped or tested it

## Tell us more about the current state of your project idea.

Replicate Street Art Orlando - a project done by the Orlando Brigade - for our community.  See 
https://github.com/cforlando/street-art-orlando-ios, 
https://github.com/cforlando/street-art-orlando-api, and 
https://github.com/cforlando/street-art-orlando-website
http://streetartorlando.com/

## Tell us about yourself. 

I am a Swift developer and was looking for any Code for America project that I might be able to contribute to.  I stumbled upon this project done by the Orlando brigade, contacted the author, and he offered for us to fork it and customized a version for Ft Lauderdale.  So that is what I would like to to do.

**Comment by ryanvgates** [comment]
Do you have a link to the working website for Orlando?

**Comment by jslusser** [comment]
http://streetartorlando.com/    Per Axel, the author, it turns out the website is simply a landing page for the project, but there’s no website. It’s only a mobile app + api.

**Comment by qtrandev** [comment]
@jslusser Let me know if you need any repo cloned or created. I can't help much on the Ruby side but I like the idea.

**Comment by ryanvgates** [comment]
@jslusser hey, how are things going with this project? What would you want from new volunteers?

**Comment by ryanvgates** [comment]
I'm going to close this issue due to lack of activity. If that changes, it can be re-opened.
