### ISSUE TITLE
Bail Project - South Florida

### ISSUE THREAD

**Issue by yfrigi** [CodeForFtL/project-ideas#13]
## Short description of the idea (140 character tweet):

Bring The Bail Project to South Florida.  Starting with Broward County and then Miami-Dade and Palm Beach counties.  

## What is your project concept or idea? What challenge or opportunity will it solve?

The Bail Project is a 5-year initiative to open 40 additional sites with a goal of paying bail for 160k people.  The ultimate goal is criminal justice reform, specifically ending the injustice of bail by using data to dispel the myths of what makes people come back to court.

### Do you have photos of them? Or quotes?

People who are currently in jail who have not been convicted of anything but are there simply because they cannot afford to pay their bail.  We will hire bail disruptors to visit the jail, conduct interviews and make recommendations.  Once out of jail, give them support throughout their legal proceedings.  We will also put them in touch with local organizations depending on their individual needs.
There are many stories on the main Bail Project website and their social media.

## Issue area(s) relevant to your project idea:

- Economic Opportunity & Development
- Education
- Public Safety
- Other (Criminal Justice Reform)

## What is the current state of your project idea?

- I have an idea or **concept** of a solution, but have not yet prototyped or tested it

### Do you have any links to news articles, text, mockups, code, or data?

1)  Please watch this TED talk that explains the challenge. https://www.ted.com/talks/robin_steinberg_what_if_we_ended_the_injustice_of_bail

2)  We have the beginning of a Wix website for the local effort.  Will need help completing it.  Please contact me for access.

3)  Created a Slack channel for organizing.  You can access the workspace [here](https://join.slack.com/t/bailproject/shared_invite/enQtNTExNDU0MDQ2MDY3LTliZGQwZjUxMDY0ZTFkZmZlYjNjYmIyZmExY2E0MzEyNmMzMmIxYTA5ZTE1Y2M5ZDUzMGZkYjZiZWE1Nzc4OWM):

4)  I created a [google doc](https://docs.google.com/document/d/1FJSuRJZwTG26ifpN5ZGa5ak7PZQ92EH04Ku9UB6Lbu0/edit?usp=sharing) with my notes for further details.

5)  Would like to create or take advantage of an existing app for announcing roles needed and volunteers for roles.  We already have many people who have expressed interest in helping but no way to assign tasks to them for now.  Ideas are welcome.

### Are you representing a group in submitting this project idea? 

I am very interested in reversing the injustices in our justice system.  I'm also interested in getting to know who are judges are, and the power of our jurors when using jury nullification.  I am not representing a group.  I'm just a volunteer making a difference.

**Comment by camilopayan** [comment]
Joined the slack to chat about this, and I think this is an excellent project!

**Comment by ryanvgates** [comment]
@camilopayan thank you for joining. How's everything going with the Bail Project @yfrigi ?

**Comment by ryanvgates** [comment]
Closed due to lack of updates/status. I can re-open if we know what to do next and what you'd want from volunteers.
