### ISSUE TITLE
Criminal Record Expungement

### ISSUE THREAD

**Issue by camilopayan** [CodeForFtL/project-ideas#15]
## Short description of the idea (140 character tweet):

Support for people trying to get a criminal record sealed or expunged in Florida.

## What is your project concept or idea? What challenge or opportunity will it solve?

The project starts with an [upcoming one stop shop record expungement event on July 25th](http://www.sao17.state.fl.us/assets/07-25-2019-workshop.pdf). The process is complicated, repetitive, and manual, so it seems ripe for some technological glue to speed the process.

## Who will benefit from your project? Describe the humans at the center of the problem - who are they? 

The people who would benefit are folks who have been arrested of crimes and can get their record sealed or expunged, giving them a big leg up on being able to provide for themselves and their dependents, making it easier to get good-paying work. Other beneficiaries would be lawyers working for the communities that would benefit the most from record expungement.

### How would they benefit? Can you tell their story?

We can't necessarily tell their stories, but are reaching out to organizations that do this work to find out more. Offhand, a criminal record can be a major barrier to getting well-paid jobs, especially secure public-sector jobs. Sealing or expunging a criminal record can help a person turn their life around and stabilize their situation.

### Do you have photos of them? Or quotes?

No

## Issue area(s) relevant to your project idea:

- Economic Opportunity & Development
- Neighborhoods
- Public Safety

## What is the current state of your project idea?

- I have a **fuzzy** area of opportunity but don’t yet fully understand the challenge

## Tell us more about the current state of your project idea.

Currently reaching out to organizations like the National Lawyer's Guild and Legal Aid of Broward to find out more about the expungement process and needs.

### Do you have any links to news articles, text, mockups, code, or data?

[Kansas City CfA initiative on the same project](https://www.kcur.org/post/lawyers-and-coders-team-help-ex-offenders-clear-their-records-kansas-city#stream/0)

#### Private Lawyer Expungement Pages

* [https://www.leifertlaw.com/ft-lauderdale-criminal/expungement-lawyer/](https://www.leifertlaw.com/ft-lauderdale-criminal/expungement-lawyer/)
* [https://www.browardcriminalteam.com/expunction-sealing-of-records/](https://www.browardcriminalteam.com/expunction-sealing-of-records/)
* [https://www.broward-county-criminal-attorney.com/sealing-and-expungement.html](https://www.broward-county-criminal-attorney.com/sealing-and-expungement.html)
* [https://www.defendbrowardarrest.com/sealing-records-and-expungement.html](https://www.defendbrowardarrest.com/sealing-records-and-expungement.html)

[Sealing and Expungement Program](http://www.sao17.state.fl.us/assets/preliminary-application-in-house-program-flyer-for-website.pdf)

[State's Attorney Satz Expungement Page](http://www.sao17.state.fl.us/sealexpunge.html)

**Comment by camilopayan** [comment]
Currently @RobDavis has some emails out to Broward Legal Aid and the National Lawyer's Guild to find out more about the expungement process.

Might be worthwhile to contact the Urban League and find out who is going to be present and volunteering at the expungement event on 7/25

**Comment by ryanvgates** [comment]
@camilopayan Do you know anyone at the Urban League that we could contact? Do you have more information on the expungement event on 7/25?

**Comment by camilopayan** [comment]
@ryanvgates Nope! That's definitely got to be a phone call for next week

I've been looking through the code for the existing expungement program from Philly and it seems very tailored to their needs, but hopefully we (a) don't need to use the exact PDF that the state's attorney has on their website and (b) can change it quickly.

**Comment by camilopayan** [comment]
So after calling around a bit, I ended up just having to call the State's Attorney's office, and a very nice lady told me that all their volunteers have to come from the State's Attorney after having done a security awareness training. Also, she was adamant that any software must go through a regular procurement process.

I'm not sure that this particular expungement day event, since it is entirely through the State's Attorney's office, is something we'll be able to help with.

On the other hand, the linked Kansas City event was actually done by a the UMKC law school, so maybe it's worth it to reach out to the law schools at St Thomas or Nova to find out if there are any community based events in a similar vein.

**Comment by camilopayan** [comment]
In the meantime, I'm going to poke around at the existing codebase, to get a better idea of how it works and how to deploy it.

**Comment by RobDavis** [comment]
Awesome, interesting finds Camilo. NSU has done one in the past it seems,
perhaps that contact person is still onboard at NSU;
https://nsunews.nova.edu/nsus-veterans-law-clinic-offer-free-workshop-removing-legal-barriers-employment/
cassidyj@nsu.law.nova.edu
<https://bn1prd0612.outlook.com/owa/redir.aspx?C=3YC9X0Jim06BsjG487HQINQZEB71KNAIB5PRCuHtz5q61zUpwoS6zx2jWKKSNY4wImzjueX1spg.&URL=mailto%3acassidyj%40nsu.law.nova.edu>

**Comment by ryanvgates** [comment]
@camilopayan hey
just wanted to check-in see how this is going? Is it still active? If so, what would you want from volunteers?

**Comment by camilopayan** [comment]
Unfortunately, after speaking with folks from the county, it doesn't seem
doable. If we were to continue this it'd probably have to be in partnership
with some non-profit lawyers like the NLG and not the local gov't itself.

**Comment by ryanvgates** [comment]
@camilopayan Thank you for following up. With your comment above, I'm going to close this issue for now. We can always re-open it later.
