### ISSUE TITLE
Design Graphic Materials/Social Media

### ISSUE THREAD

**Issue by RobDavis** [CodeForFtL/project-ideas#5]
## Short description of the idea (140 character tweet):

We need snazzy flyers and social media graphics!

## What is your project concept or idea? What challenge or opportunity will it solve?

We need a series of flyers to engage new potential members. 
Calls to action re: using tech for good. 

### Do you have photos of them? Or quotes?

EVERYONE! 

## Issue area(s) relevant to your project idea:

- Arts & Culture
- Education
- Open Government/Transparency

## What is the current state of your project idea?

- I understand the **challenge** well but don’t yet have ideas for a solution

### Do you have any links to news articles, text, mockups, code, or data?

Canva [Link](https://www.canva.com/design/DACXs0-zi2w/I6OmEl2O37yjLxjY8_uWhg/view?utm_content=DACXs0-zi2w&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton). 

### Are you representing a group in submitting this project idea? 

Rob, coorganizer and wearer of many hats ;)

**Comment by ryanvgates** [comment]
@RobDavis how's this project going? What would you want from any volunteers?

**Comment by ryanvgates** [comment]
I'm going to close this issue due to lack of activity. If that changes, it can be re-opened.
