### ISSUE TITLE
Press Release/Blog Post for OhSnap.site

### ISSUE THREAD

**Issue by RobDavis** [CodeForFtL/project-ideas#6]
## Short description of the idea (140 character tweet):

We need help crafting a great blog post to share [Paul](https://www.meetup.com/Code-for-FTL/members/32638592/)'s story for http://ohsnap.site

## What is your project concept or idea? What challenge or opportunity will it solve?

We will then send to Sun Sentinel/Miami Herald Contacts. Ask Rob for details. 

### Do you have photos of them? Or quotes?

*MISSING*

## Issue area(s) relevant to your project idea:

- Economic Opportunity & Development
- Food/Hunger
- Health
- Open Government/Transparency
- Public Safety

## What is the current state of your project idea?

- I have an idea or **concept** of a solution, but have not yet prototyped or tested it (Early Draft Mode)

### Do you have any links to news articles, text, mockups, code, or data?

[Google Docs](https://docs.google.com/document/d/1uD2X1JRkIp-XVPgof0F2jCDyIKIoIT53NIAIsUBnA7k/edit?usp=sharing)

### Are you representing a group in submitting this project idea? 

Team effort. :) Let's tell the true stories of local people building solutions. The better we tell these stories, the more people will take it on themselves too root out problems and seek solutions. 👍

**Comment by psenior** [comment]
I just saw this.  My repository of the project is at https://github.com/psenior/oh-snap. My README.md is very short.  I'll try to flesh it out into a blog post.

**Comment by psenior** [comment]
I finished editing and proofreading the blog post.  You can check it out at http://webdev2016.piaseckifoundation.org/paul_senior/blog-post/public/index.php

**Comment by RobDavis** [comment]
Ok great, I've added it as a draft on medium and I'll add some photos I
have on my computer of you presenting shortly.

Will send back for final approval before posting.

Talk soon,
Rob

**Comment by RobDavis** [comment]
Let me know what you think and I'll publish!
I'll see if we can get a plug from CfAmerica too. Great writeup!
https://medium.com/@CodeforFTL/the-story-of-oh-snap-cfabrigade-99b73b243156

**Comment by psenior** [comment]
Rob,
Sorry I didn't respond earlier but I had an interview today at 2 PM.  You
did a great job with adding the photos to the article.  It looks
fantastic.  Go ahead and post it.  I will send an email to everyone I
mentioned in the article to get some traffic to it once it's up.
Paul

**Comment by ryanvgates** [comment]
@RobDavis @psenior should this issue be closed then?

**Comment by psenior** [comment]
Yes, please close it out.
