### ISSUE TITLE
Crowdsourced Blockchain CryptoInsurance

### ISSUE THREAD

**Issue by snovak** [CodeForFtL/project-ideas#8]
## Short description of the idea (140 character tweet):

Decentralized.
Crowdsourced.
Open Sourced.
Transparent.
INSURANCE.....
for anyone who wants it.
BOOM!

## What is your project concept or idea? What challenge or opportunity will it solve?

Blockchain IS already changing the world.  It’s a beautiful technology, with an amazing power to eliminate “the middleman”.  The fat cats getting rich off their “services” to you.  Who are the fat cats in the world today?  Mostly Financiers, Bankers, and Insurance Providers.  Cryptocurrency might serve to, in some regards, supplant the middleman for currency, the Banks of the world.  I see the possibility, through blockchain, to eliminate another middle man, the insurance company.

## Who will benefit from your project? Describe the humans at the center of the problem - who are they? 

Humans, are the beneficiary, the center of the problem, and the solution. 

### How would they benefit? Can you tell their story?
You know the whole Obamacare thing?  It's that, but better.  Though, Life insurance is a much easier target to start with being far less complex as it depends mostly on a binary variable.  You're dead, or  you're not dead.  ....and we can likely plug into a public dead/not dead database somewhere.  ;-)

### Do you have photos of them? Or quotes?
Any photo, of anyone in the world, is a photo of the person this would help.  

## Issue area(s) relevant to your project idea:

- Health 
- Housing 
- Open Government/Transparency 

## What is the current state of your project idea?

- I have an idea or **concept** of a solution, but have not yet prototyped or tested it  

## Tell us more about the current state of your project idea.
It's just an idea.  There's a few details to be worked out.  ;-)

### Do you have any links to news articles, text, mockups, code, or data?
No, Sorry.  Early stages of the idea. 

### What is your background? Why is this challenge important to you? 
My background is in Web front-end development and computer animation, and specialize in Mixed Reality Development.  I'm currently employed by SAP, but this is in no way associated.  

I think this is important to everyone.  Sort of a, 'For everyone, by everyone' project, which is why I'm bringing the idea to this group.  It can't be OWNED by any one person or group.  I think this idea/project should be totally public/non-profit to work correctly.

### Are you representing a group in submitting this project idea? 
If you would like to put 'everyone' in a group, sure.

**Comment by djilo** [comment]
This sounds intriguing. I have not been active in this group for years as I live in Colorado Springs now, but this caught my eye. I would be interested in discussing it with you. I have no real experience with blockchain, but from what I understand it could be a game changer for many domains in our life. If you're interested in talking about it with me, please contact me at the email address in my profile. I hope to hear from you.

**Comment by snovak** [comment]
This is my second time attending a Code for Fort Lauderdale meetup, I'm literally sitting in the meetup as I write this.  To be totally honest, I'm no blockchain expert either, having never picked up and worked with it on a project.  But, I understand the basics of it fairly well, and a decent developer in general.  Are you on the Slack channel for Code for FTL as well?

**Comment by djilo** [comment]
No, I'm not on the Slack channel. Can you invite me?

**Comment by snovak** [comment]
I will request for you to be invited.

**Comment by djilo** [comment]
Thanks!

**Comment by ryanvgates** [comment]
@snovak @djilo how's this project going? What would you want from any new volunteers?

**Comment by ryanvgates** [comment]
I'm going to close this issue due to lack of activity. If that changes, it can be re-opened.
