### ISSUE TITLE
Twitter bot for fire alerts

### ISSUE THREAD

**Issue by RobDavis** [CodeForFtL/project-ideas#9]
## Short description of the idea (140 character tweet):

Twitter Bot

## What is your project concept or idea? What challenge or opportunity will it solve?

Notifying followers of Fire updates. 

### Do you have photos of them? Or quotes?

People who use twitter. Nope. 

## Issue area(s) relevant to your project idea:

- Environment 
- Health

## What is the current state of your project idea?

- I have an idea or **concept** of a solution, but have not yet prototyped or tested it

### Do you have any links to news articles, text, mockups, code, or data?

_Your answer_

### Are you representing a group in submitting this project idea? 

_Your answer_

**Comment by lamvann** [comment]
Hey there, I attended a CodeForFTL meeting last night and I am interested in knowing what would the first steps be to get the twitter bot going?

**Comment by ryanvgates** [comment]
I sent the following [tweet](https://twitter.com/ryanvgates/status/1002598869375574016) to @EvergladesNPS . I emailed using the [contact form](https://www.nps.gov/ever/contacts.htm) at  asking for the same and about their rss feed on [this page](https://www.nps.gov/ever/learn/news/everglades-national-park-to-conduct-prescribed-burn-this-week.htm). I'll let you know when I hear anything back.

**Comment by lamvann** [comment]
Hey, just wanted to follow up real quick on this issue and inquire if there are any new developments?

**Comment by ryanvgates** [comment]
@lamvann Unfortunately I haven't heard anything back. I'll try to call some of the numbers listed and let you know what I find out.

**Comment by qtrandev** [comment]
Heard someone else was working on a Twitter Bot a while ago, wonder if he has any info one creating one.

**Comment by ryanvgates** [comment]
@qtrandev do you know who was working on a Twitter Bot?

**Comment by qtrandev** [comment]
I believe he was Lucas Meyer from Microsoft. He said he could create a Twitter Bot quickly. If you see him again, you could get more details. I think he would use Azure but if you google Twitter Bot online, there's tutorials for AWS Lambda which seems inexpensive or free. I think a first step could be to create a bot that retweets anyone who mentions "everglades fire" first even without our own data, then work off that to eventually tweet on real fire 🔥 data. data .

**Comment by ryanvgates** [comment]
@qtrandev that's a good point. We can start doing the twitter bot sans data while trying to get the data.

**Comment by lamvann** [comment]
Hey guys, here's some updates: 

-Made both gmail and twitter accounts for the bot. 
-Applied for the developer access to the Twitter API and it's on the waiting list for the moment. 
-Wrote a twitter bot in Python but need Dev access to test it on the account.
-Once API access is granted all we'd need is to link it with the Everglades services.

**Comment by lamvann** [comment]
Hey there,
-The developer account was approved by twitter today.
-Twitter handler is @FireEverglades
-Twitter bot successfully tweets automatically through API
-We now need data to move forward.

Cheers!

**Comment by qtrandev** [comment]
@lamvann Can you post the code for this in a repo somewhere? Also if you used a tutorial on how to create the bot, add the link to it here. We want to teach people to the steps to create something like this customized to what we are doing for the Everglades.

https://twitter.com/EvergladesNPS doesn't tweet that often, so a better account to retweet is https://twitter.com/FFS_Everglades

#everglades #prescribedfire might be the hashtags to use with every post.

It's not something easy, but your bot could try to do a Google search for "everglades controlled burn" and tweet the latest article it finds as a start.
https://news.google.com/search?q=everglades%20controlled%20burn

**Comment by ryanvgates** [comment]
@lamvann @qtrandev @RobDavis how's this project going? What would you want from any volunteers to help it along?

**Comment by ryanvgates** [comment]
I'm going to close this idea due to lack of activity. If that changes, we can always re-open it.
